databank/accounts/urls.py
from django.urls import path

from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

databank/databank/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('pages.urls')),
]

databank/pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('notes/', views.NotePostList.as_view(), name="notes"),
    path('<slug:slug>/', views.NotePostDetail.as_view(), name="notepost_detail"),
    path('about/', views.about, name="about"),  
]

databank/accounts/models.py
from django.db import models

# Create your models here.

databank/pages/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE

STATUS = (
    (0, "Draft"),
    (1, "Publish")
)

class NotePost(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    subject = models.CharField(max_length=200, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="note_posts")
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

databank/accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

databank/pages/views.py
from django.shortcuts import render
from django.views import generic

from .models import NotePost

class NotePostList(generic.ListView):
    queryset = NotePost.objects.filter(status=1).order_by('-created_on')
    template_name = "pages/notes.html"

class NotePostDetail(generic.DetailView):
    model = NotePost
    template_name = "pages/notepost_detail.html"

def home(request):
    context = {}
    return render(request, 'pages/home.html', context) 

# def notes(request):
    # context = {}
    # return render(request, 'pages/notes.html', context)

def about(request):
    context = {}
    return render(request, 'pages/about.html', context)

databank/templates/main.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>{% block title %}Databank{% endblock title %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    </head>

    <body>
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'home' %}">Databank</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'about' %}">About</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'notes' %}">Notes</a>
                            </li>
                        </ul>
                        <form class="d-flex">
                            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-secondary" type="submit">Search</button>
                        </form>
                        <div class="divider"></div>
                        {% if user.is_authenticated %}
                            <a class="btn btn-outline-danger" href="{% url 'logout' %}" role="button">Logout</a>
                        {% else %}
                            <a class="btn btn-outline-success" href="{% url 'login' %}" role="button">Login</a>
                        {% endif %}
                        </form>
                    </div>
                </div>
            </nav>
        </header>

        <main>
            {% block content %}

            {% endblock content %}
        </main>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    </body>
</html>

databank/templates/pages/about.html
{% extends 'main.html' %}
{% load static %}

{% block title %}About{% endblock title %}

{% block content %}

<h2>About</h2>

{% endblock content %}

databank/templates/pages/home.html
{% extends 'main.html' %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block content %}

<div class="welcome">
    {% if user.is_authenticated %}
        Welcome, {{ user.username }}
        <P><a href="{% url 'logout' %}">Log Out</a></P>
    {% else %}
        <p>You are not loggin in</p>
        <a href="{% url 'login' %}"">Login</a>
    {% endif %}
</div>

{% endblock content %}

databank/templates/pages/notepost_detail.html
{% extends 'main.html' %} 
{% load static %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left mx-auto">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ notepost.author }} | {{ notepost.created_on }}</p>
        <p class="card-text ">{{ object.content | safe }}</p>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

databank/templates/pages/notes.html
{% extends 'main.html' %}
{% load static %}

{% block title %}Notes{% endblock title %}

{% block content %}

<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }
    
    .head_text {
        color: white;
    }
    
    .card {
        box-shadow: 0 16px 48px #E3E7EB;
        text-align: center;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h2 class=" site-heading my-4 mt-3 text-white"> Notes </h2>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 mx-auto">
            {% for post in notepost_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.subject }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.content|slice:":100" }}</p>
                    <a href="{% url 'notepost_detail' post.slug  %}" class="btn btn-primary">Read&rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
      
    </div>
</div>

{% endblock content %}

databank/templates/sidebar.html
{% block sidebar %}

    <style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB
        }
    </style>

    <!-- Sidebar Widgets Column -->
    <div class="col-md-4 float-right ">
    <div class="card my-4">
            <h5 class="card-header">About Us</h5>
        <div class="card-body">
            <p class="card-text"> This awesome blog is made on the top of our Favourite full stack Framework 'Django', follow up the tutorial to learn how we made it..!</p>
            <a href="https://djangocentral.com/building-a-blog-application-with-django"
            class="btn btn-danger">Know more!</a>
        </div>
    </div>
    </div>

{% endblock sidebar %}